version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 424242
      POSTGRES_DB: case_study_db
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5432:5432"

  web:
    build: .
    command: python run.py
    volumes:
      - .:/code
    ports:
      - "5001:5001"
    depends_on:
      - db
